### ISSUE TITLE
Can u share a video on youtube?

### ISSUE THREAD

**Issue by watershade** [marando/pycatfd#3]
Sorry about this question. I want to know if your program perform good enough.
I find it is hard to use. First, you need install opencv2( I install opencv3 before). And I need build dlib on my computer. But the most trick part is I want to move it to raspberry pi zero.

Sorry about it. If it just a samll test project. Youcan tell me. Thanks.

**Comment by marando** [comment]
The more data you gave it the better it would perform, currently the trained model does not have a massive amount of data so it is not the most accurate, and there's some issues with detecting rotated or skewed faces in 3D space that I might want to explore fixing in the future.

Anyway, I have not worked with a Raspberry PI yet (really want to), but you could probably use the [Dockerfile](https://github.com/marando/pycatfd/blob/master/Dockerfile) I just pushed as a basis for some of the dependencies and items that will need to be installed for it to function. Let me know if you have any questions and sorry for not being able to reply for so long.

**Comment by watershade** [comment]
Thanks man!
