### ISSUE TITLE
draw_line function parameter name change 

### ISSUE THREAD

**Issue by mauckc** [marando/pycatfd#4]
Using OpenCV version 3.4.1
I needed to change line 221 from "cv2.CV_AA" -> "cv2.LINE_AA"

```python
    cv2.line(img, pt1, pt2, color, width, cv2.CV_AA)
```
...becomes:
```python
    cv2.line(img, pt1, pt2, color, width, cv2.LINE_AA) 
```

**Comment by marando** [comment]
Thanks, I actually worked that into some new changes I pushed to master.

**Comment by mauckc** [comment]
Great, thanks! I will check it out.

Next time I should do a pull request then?
